#!/bin/bash

echo "🚀 Apex Lead Qualification System Setup"
echo "======================================"
echo ""
echo "📋 Step 1: Create Database Tables"
echo "Please run the following SQL in your Supabase SQL Editor:"
echo ""
echo "File location: apps/backend/create-qualification-tables.sql"
echo ""
echo "OR copy this command to create tables via API:"
echo ""
echo "node run-lead-qualification-schema.js"
echo ""
echo "======================================"
echo ""
echo "📝 Step 2: Insert Preset Fields"
echo "After tables are created, run:"
echo ""
echo "node insert-preset-fields.js"
echo ""
echo "======================================"
echo ""
echo "✅ Step 3: Verify Setup"
echo "Check these tables in Supabase:"
echo "- qualification_field_presets (should have 22 rows)"
echo "- campaign_qualification_fields"
echo "- campaign_custom_fields"
echo "- lead_qualification_data"
echo "- campaigns.winning_criteria column"
echo ""
echo "======================================"
echo ""
echo "📚 Full guide: LEAD_QUALIFICATION_SETUP_GUIDE.md"
echo ""

# Make the file executable
chmod +x quick-setup-qualification.sh